cxx_binary(
  name = 'server',
  header_namespace = '',
  headers = subdir_glob([
    ('', '*.h'),
  ]),
  srcs = glob([
    '*.cpp',
  ]),
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:fruit',
  ],
)
